<div class="blog-list-table-container">
    <table class="blog-list-table">
        <tr class="blog-list-table-head">
            <th class="blog-list-table-id">
                <?= __("Id")?>
            </th>
            <th class="blog-list-table-title">
                <?= __("Title")?>
            </th>
            <th class="blog-list-table-content">
                <?= __("Content")?>
            </th>
            <th class="blog-list-table-action-edit">
                <?= __("Edit") ?>
            </th>
            <th class="blog-list-table-action-delete">
                <?= __("Delete") ?>
            </th>
        </tr>
        <?php
        $blogs = $block->getBlogs();

        foreach ($blogs as $blog) {?>
            <tr>
                <td>
                    <?= $blog->getId()?>
                </td>
                <td>
                    <?= $blog->getTitle()?>
                </td>
                <td>
                    <?= substr($blog->getContent(), 0, 20).'...'?>
                </td>
                <td class="blog-list-table-action blog-list-table-action-edit">
                    <a href="<?php echo $block->getUrl('blog/manage/edit', ['id'=>$blog->getId()]); ?>">
                        <?= __('Edit') ?>
                    </a>
                </td>
                <td class="blog-list-table-action blog-list-table-action-delete">
                    <a href="<?php echo $block->getUrl('blog/manage/delete', ['id'=>$blog->getId()]); ?>">
                        <?= __('Delete') ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "bloglist": ""
        }
    }
</script>
